nominal:
  goal:
    coordinates:
      - 0.0
      - 2.2
      - 1.3
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    gain:
    - [0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0]
    - [-0.4, 0.0, 0.0, -0.4, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -4.4721]
    - [0.0, 0.0, -5.4772, 0.0, 0.0, -5.5637, 0.0]
  frequency: 10.0
cbf:
  gamma: 0.2